### ISSUE TITLE
Why this if there is Firmata already?

### ISSUE THREAD

**Issue by q2dg** [nuket/arduino-shell#9]
I only want to know if this project gives something different. Thanks

**Comment by nuket** [comment]
Firmata looks a bit different to this, this project is designed to allow roughly-speaking, command-line interaction with the software using human-readable strings when using the Serial Monitor in Arduino IDE. 

Firmata seems to be based on MIDI message formatting, and probably transmits values directly in binary.

**Comment by q2dg** [comment]
No. See https://github.com/firmata/arduino
